[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
regex = "1.10.2"

[dev-dependencies]
insta = { version = "1.34.0", features = ["yaml"] }

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
